services:
  - type: web
    name: sentra
    runtime: node
    buildCommand: bash build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
